<script setup lang="ts">
import { ref, watch } from 'vue';
import { percentageOfTotal } from '@snapshot-labs/snapshot.js/src/voting/quadratic';
import { useMediaQuery } from '@vueuse/core';

// Dynamic circles for diamond
const circles = [...Array(100)].map((x, item) => {
  return {};
});
</script>

<template>
  <div>
    <svg
      width="220"
      height="220"
      viewBox="0 0 220 220"
      xmlns="http://www.w3.org/2000/svg"
    >
      <g transform="translate(220,110)">
        <circle
          id="diamond-0"
          r="5"
          cx="-20"
          cy="0"
          data-level="1"
          data-ai="0"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-2"
          r="5"
          cx="-40"
          cy="0"
          data-level="2"
          data-ai="0"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-1"
          r="5"
          cx="-30"
          cy="-10"
          data-level="2"
          data-ai="1"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-3"
          r="5"
          cx="-30"
          cy="10"
          data-level="2"
          data-ai="2"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-6"
          r="5"
          cx="-60"
          cy="0"
          data-level="3"
          data-ai="0"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-5"
          r="5"
          cx="-50"
          cy="-10"
          data-level="3"
          data-ai="1"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-7"
          r="5"
          cx="-50"
          cy="10"
          data-level="3"
          data-ai="2"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-4"
          r="5"
          cx="-40"
          cy="-20"
          data-level="3"
          data-ai="3"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-8"
          r="5"
          cx="-40"
          cy="20"
          data-level="3"
          data-ai="4"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-12"
          r="5"
          cx="-80"
          cy="0"
          data-level="4"
          data-ai="0"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-11"
          r="5"
          cx="-70"
          cy="-10"
          data-level="4"
          data-ai="1"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-13"
          r="5"
          cx="-70"
          cy="10"
          data-level="4"
          data-ai="2"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-10"
          r="5"
          cx="-60"
          cy="-20"
          data-level="4"
          data-ai="3"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-14"
          r="5"
          cx="-60"
          cy="20"
          data-level="4"
          data-ai="4"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-9"
          r="5"
          cx="-50"
          cy="-30"
          data-level="4"
          data-ai="5"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-15"
          r="5"
          cx="-50"
          cy="30"
          data-level="4"
          data-ai="6"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-20"
          r="5"
          cx="-100"
          cy="0"
          data-level="5"
          data-ai="0"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-19"
          r="5"
          cx="-90"
          cy="-10"
          data-level="5"
          data-ai="1"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-21"
          r="5"
          cx="-90"
          cy="10"
          data-level="5"
          data-ai="2"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-18"
          r="5"
          cx="-80"
          cy="-20"
          data-level="5"
          data-ai="3"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-22"
          r="5"
          cx="-80"
          cy="20"
          data-level="5"
          data-ai="4"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-17"
          r="5"
          cx="-70"
          cy="-30"
          data-level="5"
          data-ai="5"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-23"
          r="5"
          cx="-70"
          cy="30"
          data-level="5"
          data-ai="6"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-16"
          r="5"
          cx="-60"
          cy="-40"
          data-level="5"
          data-ai="7"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-24"
          r="5"
          cx="-60"
          cy="40"
          data-level="5"
          data-ai="8"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-30"
          r="5"
          cx="-120"
          cy="0"
          data-level="6"
          data-ai="0"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-29"
          r="5"
          cx="-110"
          cy="-10"
          data-level="6"
          data-ai="1"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-31"
          r="5"
          cx="-110"
          cy="10"
          data-level="6"
          data-ai="2"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-28"
          r="5"
          cx="-100"
          cy="-20"
          data-level="6"
          data-ai="3"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-32"
          r="5"
          cx="-100"
          cy="20"
          data-level="6"
          data-ai="4"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-27"
          r="5"
          cx="-90"
          cy="-30"
          data-level="6"
          data-ai="5"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-33"
          r="5"
          cx="-90"
          cy="30"
          data-level="6"
          data-ai="6"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-26"
          r="5"
          cx="-80"
          cy="-40"
          data-level="6"
          data-ai="7"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-34"
          r="5"
          cx="-80"
          cy="40"
          data-level="6"
          data-ai="8"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-25"
          r="5"
          cx="-70"
          cy="-50"
          data-level="6"
          data-ai="9"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-35"
          r="5"
          cx="-70"
          cy="50"
          data-level="6"
          data-ai="10"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-42"
          r="5"
          cx="-140"
          cy="0"
          data-level="7"
          data-ai="0"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-41"
          r="5"
          cx="-130"
          cy="-10"
          data-level="7"
          data-ai="1"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-43"
          r="5"
          cx="-130"
          cy="10"
          data-level="7"
          data-ai="2"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-40"
          r="5"
          cx="-120"
          cy="-20"
          data-level="7"
          data-ai="3"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-44"
          r="5"
          cx="-120"
          cy="20"
          data-level="7"
          data-ai="4"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-39"
          r="5"
          cx="-110"
          cy="-30"
          data-level="7"
          data-ai="5"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-45"
          r="5"
          cx="-110"
          cy="30"
          data-level="7"
          data-ai="6"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-38"
          r="5"
          cx="-100"
          cy="-40"
          data-level="7"
          data-ai="7"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-46"
          r="5"
          cx="-100"
          cy="40"
          data-level="7"
          data-ai="8"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-37"
          r="5"
          cx="-90"
          cy="-50"
          data-level="7"
          data-ai="9"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-47"
          r="5"
          cx="-90"
          cy="50"
          data-level="7"
          data-ai="10"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-36"
          r="5"
          cx="-80"
          cy="-60"
          data-level="7"
          data-ai="11"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-48"
          r="5"
          cx="-80"
          cy="60"
          data-level="7"
          data-ai="12"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-56"
          r="5"
          cx="-160"
          cy="0"
          data-level="8"
          data-ai="0"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-55"
          r="5"
          cx="-150"
          cy="-10"
          data-level="8"
          data-ai="1"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-57"
          r="5"
          cx="-150"
          cy="10"
          data-level="8"
          data-ai="2"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-54"
          r="5"
          cx="-140"
          cy="-20"
          data-level="8"
          data-ai="3"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-58"
          r="5"
          cx="-140"
          cy="20"
          data-level="8"
          data-ai="4"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-53"
          r="5"
          cx="-130"
          cy="-30"
          data-level="8"
          data-ai="5"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-59"
          r="5"
          cx="-130"
          cy="30"
          data-level="8"
          data-ai="6"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-52"
          r="5"
          cx="-120"
          cy="-40"
          data-level="8"
          data-ai="7"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-60"
          r="5"
          cx="-120"
          cy="40"
          data-level="8"
          data-ai="8"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-51"
          r="5"
          cx="-110"
          cy="-50"
          data-level="8"
          data-ai="9"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-61"
          r="5"
          cx="-110"
          cy="50"
          data-level="8"
          data-ai="10"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-50"
          r="5"
          cx="-100"
          cy="-60"
          data-level="8"
          data-ai="11"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-62"
          r="5"
          cx="-100"
          cy="60"
          data-level="8"
          data-ai="12"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-49"
          r="5"
          cx="-90"
          cy="-70"
          data-level="8"
          data-ai="13"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-63"
          r="5"
          cx="-90"
          cy="70"
          data-level="8"
          data-ai="14"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-72"
          r="5"
          cx="-180"
          cy="0"
          data-level="9"
          data-ai="0"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-71"
          r="5"
          cx="-170"
          cy="-10"
          data-level="9"
          data-ai="1"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-73"
          r="5"
          cx="-170"
          cy="10"
          data-level="9"
          data-ai="2"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-70"
          r="5"
          cx="-160"
          cy="-20"
          data-level="9"
          data-ai="3"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-74"
          r="5"
          cx="-160"
          cy="20"
          data-level="9"
          data-ai="4"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-69"
          r="5"
          cx="-150"
          cy="-30"
          data-level="9"
          data-ai="5"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-75"
          r="5"
          cx="-150"
          cy="30"
          data-level="9"
          data-ai="6"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-68"
          r="5"
          cx="-140"
          cy="-40"
          data-level="9"
          data-ai="7"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-76"
          r="5"
          cx="-140"
          cy="40"
          data-level="9"
          data-ai="8"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-67"
          r="5"
          cx="-130"
          cy="-50"
          data-level="9"
          data-ai="9"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-77"
          r="5"
          cx="-130"
          cy="50"
          data-level="9"
          data-ai="10"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-66"
          r="5"
          cx="-120"
          cy="-60"
          data-level="9"
          data-ai="11"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-78"
          r="5"
          cx="-120"
          cy="60"
          data-level="9"
          data-ai="12"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-65"
          r="5"
          cx="-110"
          cy="-70"
          data-level="9"
          data-ai="13"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-79"
          r="5"
          cx="-110"
          cy="70"
          data-level="9"
          data-ai="14"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-64"
          r="5"
          cx="-100"
          cy="-80"
          data-level="9"
          data-ai="15"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-80"
          r="5"
          cx="-100"
          cy="80"
          data-level="9"
          data-ai="16"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-90"
          r="5"
          cx="-200"
          cy="0"
          data-level="10"
          data-ai="0"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-89"
          r="5"
          cx="-190"
          cy="-10"
          data-level="10"
          data-ai="1"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-91"
          r="5"
          cx="-190"
          cy="10"
          data-level="10"
          data-ai="2"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-88"
          r="5"
          cx="-180"
          cy="-20"
          data-level="10"
          data-ai="3"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-92"
          r="5"
          cx="-180"
          cy="20"
          data-level="10"
          data-ai="4"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-87"
          r="5"
          cx="-170"
          cy="-30"
          data-level="10"
          data-ai="5"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-93"
          r="5"
          cx="-170"
          cy="30"
          data-level="10"
          data-ai="6"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-86"
          r="5"
          cx="-160"
          cy="-40"
          data-level="10"
          data-ai="7"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-94"
          r="5"
          cx="-160"
          cy="40"
          data-level="10"
          data-ai="8"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-85"
          r="5"
          cx="-150"
          cy="-50"
          data-level="10"
          data-ai="9"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-95"
          r="5"
          cx="-150"
          cy="50"
          data-level="10"
          data-ai="10"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-84"
          r="5"
          cx="-140"
          cy="-60"
          data-level="10"
          data-ai="11"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-96"
          r="5"
          cx="-140"
          cy="60"
          data-level="10"
          data-ai="12"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-83"
          r="5"
          cx="-130"
          cy="-70"
          data-level="10"
          data-ai="13"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-97"
          r="5"
          cx="-130"
          cy="70"
          data-level="10"
          data-ai="14"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-82"
          r="5"
          cx="-120"
          cy="-80"
          data-level="10"
          data-ai="15"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-98"
          r="5"
          cx="-120"
          cy="80"
          data-level="10"
          data-ai="16"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-81"
          r="5"
          cx="-110"
          cy="-90"
          data-level="10"
          data-ai="17"
          fill="#E1DFD0"
        ></circle>
        <circle
          id="diamond-99"
          r="5"
          cx="-110"
          cy="90"
          data-level="10"
          data-ai="18"
          fill="#E1DFD0"
        ></circle>
      </g>
    </svg>
  </div>
</template>
