<script setup>
import { ref, watch } from 'vue';
import { percentageOfTotal } from '@snapshot-labs/snapshot.js/src/voting/quadratic';
import { useMediaQuery } from '@vueuse/core';
</script>

<template>
  <div>
    <svg
      width="220"
      height="220"
      viewBox="0 0 220 220"
      xmlns="http://www.w3.org/2000/svg"
    >
      <g transform="translate(220,110)">
        <circle
          id="diamond-1"
          r="5"
          cx="-20"
          cy="0"
          data-level="1"
          data-ai="0"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-40"
          cy="0"
          data-level="2"
          data-ai="0"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-30"
          cy="-10"
          data-level="2"
          data-ai="1"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-30"
          cy="10"
          data-level="2"
          data-ai="2"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-60"
          cy="0"
          data-level="3"
          data-ai="0"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-50"
          cy="-10"
          data-level="3"
          data-ai="1"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-50"
          cy="10"
          data-level="3"
          data-ai="2"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-40"
          cy="-20"
          data-level="3"
          data-ai="3"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-40"
          cy="20"
          data-level="3"
          data-ai="4"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-80"
          cy="0"
          data-level="4"
          data-ai="0"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-70"
          cy="-10"
          data-level="4"
          data-ai="1"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-70"
          cy="10"
          data-level="4"
          data-ai="2"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-60"
          cy="-20"
          data-level="4"
          data-ai="3"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-60"
          cy="20"
          data-level="4"
          data-ai="4"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-50"
          cy="-30"
          data-level="4"
          data-ai="5"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-50"
          cy="30"
          data-level="4"
          data-ai="6"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-100"
          cy="0"
          data-level="5"
          data-ai="0"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-90"
          cy="-10"
          data-level="5"
          data-ai="1"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-90"
          cy="10"
          data-level="5"
          data-ai="2"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-80"
          cy="-20"
          data-level="5"
          data-ai="3"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-80"
          cy="20"
          data-level="5"
          data-ai="4"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-70"
          cy="-30"
          data-level="5"
          data-ai="5"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-70"
          cy="30"
          data-level="5"
          data-ai="6"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-60"
          cy="-40"
          data-level="5"
          data-ai="7"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-60"
          cy="40"
          data-level="5"
          data-ai="8"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-120"
          cy="0"
          data-level="6"
          data-ai="0"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-110"
          cy="-10"
          data-level="6"
          data-ai="1"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-110"
          cy="10"
          data-level="6"
          data-ai="2"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-100"
          cy="-20"
          data-level="6"
          data-ai="3"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-100"
          cy="20"
          data-level="6"
          data-ai="4"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-90"
          cy="-30"
          data-level="6"
          data-ai="5"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-90"
          cy="30"
          data-level="6"
          data-ai="6"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-80"
          cy="-40"
          data-level="6"
          data-ai="7"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-80"
          cy="40"
          data-level="6"
          data-ai="8"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-70"
          cy="-50"
          data-level="6"
          data-ai="9"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-70"
          cy="50"
          data-level="6"
          data-ai="10"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-140"
          cy="0"
          data-level="7"
          data-ai="0"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-130"
          cy="-10"
          data-level="7"
          data-ai="1"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-130"
          cy="10"
          data-level="7"
          data-ai="2"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-120"
          cy="-20"
          data-level="7"
          data-ai="3"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-120"
          cy="20"
          data-level="7"
          data-ai="4"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-110"
          cy="-30"
          data-level="7"
          data-ai="5"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-110"
          cy="30"
          data-level="7"
          data-ai="6"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-100"
          cy="-40"
          data-level="7"
          data-ai="7"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-100"
          cy="40"
          data-level="7"
          data-ai="8"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-90"
          cy="-50"
          data-level="7"
          data-ai="9"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-90"
          cy="50"
          data-level="7"
          data-ai="10"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-80"
          cy="-60"
          data-level="7"
          data-ai="11"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-80"
          cy="60"
          data-level="7"
          data-ai="12"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-160"
          cy="0"
          data-level="8"
          data-ai="0"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-150"
          cy="-10"
          data-level="8"
          data-ai="1"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-150"
          cy="10"
          data-level="8"
          data-ai="2"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-140"
          cy="-20"
          data-level="8"
          data-ai="3"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-140"
          cy="20"
          data-level="8"
          data-ai="4"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-130"
          cy="-30"
          data-level="8"
          data-ai="5"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-130"
          cy="30"
          data-level="8"
          data-ai="6"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-120"
          cy="-40"
          data-level="8"
          data-ai="7"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-120"
          cy="40"
          data-level="8"
          data-ai="8"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-110"
          cy="-50"
          data-level="8"
          data-ai="9"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-110"
          cy="50"
          data-level="8"
          data-ai="10"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-100"
          cy="-60"
          data-level="8"
          data-ai="11"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-100"
          cy="60"
          data-level="8"
          data-ai="12"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-90"
          cy="-70"
          data-level="8"
          data-ai="13"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-90"
          cy="70"
          data-level="8"
          data-ai="14"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-180"
          cy="0"
          data-level="9"
          data-ai="0"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-170"
          cy="-10"
          data-level="9"
          data-ai="1"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-170"
          cy="10"
          data-level="9"
          data-ai="2"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-160"
          cy="-20"
          data-level="9"
          data-ai="3"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-160"
          cy="20"
          data-level="9"
          data-ai="4"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-150"
          cy="-30"
          data-level="9"
          data-ai="5"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-150"
          cy="30"
          data-level="9"
          data-ai="6"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-140"
          cy="-40"
          data-level="9"
          data-ai="7"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-140"
          cy="40"
          data-level="9"
          data-ai="8"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-130"
          cy="-50"
          data-level="9"
          data-ai="9"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-130"
          cy="50"
          data-level="9"
          data-ai="10"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-120"
          cy="-60"
          data-level="9"
          data-ai="11"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-120"
          cy="60"
          data-level="9"
          data-ai="12"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-110"
          cy="-70"
          data-level="9"
          data-ai="13"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-110"
          cy="70"
          data-level="9"
          data-ai="14"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-100"
          cy="-80"
          data-level="9"
          data-ai="15"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-100"
          cy="80"
          data-level="9"
          data-ai="16"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-200"
          cy="0"
          data-level="10"
          data-ai="0"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-190"
          cy="-10"
          data-level="10"
          data-ai="1"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-190"
          cy="10"
          data-level="10"
          data-ai="2"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-180"
          cy="-20"
          data-level="10"
          data-ai="3"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-180"
          cy="20"
          data-level="10"
          data-ai="4"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-170"
          cy="-30"
          data-level="10"
          data-ai="5"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-170"
          cy="30"
          data-level="10"
          data-ai="6"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-160"
          cy="-40"
          data-level="10"
          data-ai="7"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-160"
          cy="40"
          data-level="10"
          data-ai="8"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-150"
          cy="-50"
          data-level="10"
          data-ai="9"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-150"
          cy="50"
          data-level="10"
          data-ai="10"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-140"
          cy="-60"
          data-level="10"
          data-ai="11"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-140"
          cy="60"
          data-level="10"
          data-ai="12"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-130"
          cy="-70"
          data-level="10"
          data-ai="13"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-130"
          cy="70"
          data-level="10"
          data-ai="14"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-120"
          cy="-80"
          data-level="10"
          data-ai="15"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-120"
          cy="80"
          data-level="10"
          data-ai="16"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-110"
          cy="-90"
          data-level="10"
          data-ai="17"
          fill="#E1DFD0"
        ></circle>
        <circle
          r="5"
          cx="-110"
          cy="90"
          data-level="10"
          data-ai="18"
          fill="#E1DFD0"
        ></circle>
      </g>
    </svg>
  </div>
</template>
